### ISSUE TITLE
"The error was model was not found: Cloze# tags."

### ISSUE THREAD

**Issue by driftwood3** [c-okelly/anki-remote-decks#79]
Error:
> Hey there! It seems an error has occurred while running.
> The error was model was not found: Cloze# tags.
> If you would like me to fix it please report it here: https://github.com/c-okelly/anki-remote-decks/issues
> Please be sure to provide as much information as possible. Specifically the file the caused the error.

> Traceback (most recent call last):
>   File "/Users/bradyjohnson/Library/Application Support/Anki2/addons21/911568091/__init__.py", line 36, in addDeck
>     addNewDeck()
>   File "/Users/bradyjohnson/Library/Application Support/Anki2/addons21/911568091/remote_decks/main.py", line 143, in addNewDeck
>     ankiBridge.uploadNewDeck(deck)
>   File "/Users/bradyjohnson/Library/Application Support/Anki2/addons21/911568091/remote_decks/libs/org_to_anki/ankiConnectWrapper/AnkiPluginConnector.py", line 57, in uploadNewDeck
>     raise e
>   File "/Users/bradyjohnson/Library/Application Support/Anki2/addons21/911568091/remote_decks/libs/org_to_anki/ankiConnectWrapper/AnkiPluginConnector.py", line 52, in uploadNewDeck
>     self.AnkiBridge.addNote(note)
>   File "/Users/bradyjohnson/Library/Application Support/Anki2/addons21/911568091/remote_decks/libs/org_to_anki/ankiConnectWrapper/AnkiBridge.py", line 45, in addNote
>     ankiNote = self.createNote(note)
>   File "/Users/bradyjohnson/Library/Application Support/Anki2/addons21/911568091/remote_decks/libs/org_to_anki/ankiConnectWrapper/AnkiBridge.py", line 153, in createNote
>     raise Exception('model was not found: {}'.format(note['modelName']))
> Exception: model was not found: Cloze# tags

[Published Google Doc](https://docs.google.com/document/d/e/2PACX-1vSDCiO-P1VvyXVdAsb0--WrU2ofU01ocX-n3K4DKWeOrw-HvgJPZtMDEzJPmXjuOxJlUV9mZA2AG8yY/pub)

**Comment by c-okelly** [comment]
Hey thanks for the report.

I will look into it and get back to you
